version: '3.8'
services:
  web:
    build:
      context: ./
    
    ports:
      - "5050:5000"
    environment:
      - GREETINGS=${GREETINGS:-OK}

  curl:
    image: curlimages/curl
    command: ["curl", "web:5000/health"]